### ISSUE TITLE
uring 不能运行

### ISSUE THREAD

**Issue by sunsky** [chen622/uring-server#1]
![image](https://user-images.githubusercontent.com/570405/103516510-a6d0ad80-4eab-11eb-81b0-708331f93ca8.png)
![image](https://user-images.githubusercontent.com/570405/103516528-af28e880-4eab-11eb-9233-de8383c09d90.png)

建议添加： .gitmodules

> [submodule "liburing"]
	path = liburing
	url = https://github.com/axboe/liburing

**Comment by chen622** [comment]
好的，已添加进项目 https://github.com/chen622/uring-server/commit/59ab576a31cb75526edeb42c225b6566a6f7ebe9 。
